### ISSUE TITLE
Aula 13

### ISSUE THREAD

**Issue by IgorMichels** [maxbiostat/Statistical_Inference_BSc#10]
Percebi que no primeiro slide dessa aula existe um tópico sobre estatística pivotal, já no decorrer do slide o termo utilizado é quantidade pivotal. Isso me deixou um pouco confuso, uma vez que vimos que estatística é uma função dos dados, mas entre os exemplos de quantidade pivotal aparece um \theta S como quantidade pivotal para a exponencial.

Nesse caso, ambos os termos representam a mesma ideia?

**Comment by maxbiostat** [comment]
Uma estatística é qualquer função dos dados. Inclusive uma que envolva o(s) parâmetro(s). Desta forma, quantidade pivotal e estatística pivotal são dois nomes para a mesma coisa .

**Comment by IgorMichels** [comment]
Certo Max, entendi! Muito obrigado!
