### ISSUE TITLE
Assigment 3

### ISSUE THREAD

**Issue by wellington36** [maxbiostat/Statistical_Inference_BSc#21]
@maxbiostat, Deveria ser um ```g(\theta)``` aqui mesmo?

![image](https://user-images.githubusercontent.com/61877847/136866570-74c59ddc-cb69-4bb2-9e7f-d984b8c771e8.png)

**Comment by maxbiostat** [comment]
No caso $\delta$ **não** é eficiente (para amostras finitas). O que eu quis dizer é que se $m(\theta) = g(\theta)$ para todo $\theta$, dizemos que delta é não-viesado. Isso era só para refrescar a sua memória sobre a terminologia. Em geral, estamos interessados em estimar g(\theta) = \theta, isto é a função em questão é a identidade. Mas não custa enunciar as coisas de forma mais geral.
