### ISSUE TITLE
Doubt about question three in the assignment

### ISSUE THREAD

**Issue by wellington36** [maxbiostat/Statistical_Inference_BSc#27]
@maxbiostat In this question, it's even to derive the distributions? Doesn't seem to make sense of it.

![image](https://user-images.githubusercontent.com/61877847/185263702-9783f906-8ad4-4307-a3f3-5c09a122beda.png)

**Comment by lfzinho** [comment]
Have you figured it out? It stills confusing to me 👀

**Comment by wellington36** [comment]
> It stills confusing to me

Maybe it helps, what other sense you might have that is not differentiation, but that makes sense to do in this case.
