### ISSUE TITLE
What does "cv" mean in the assignment?

### ISSUE THREAD

**Issue by lfzinho** [maxbiostat/Statistical_Inference_BSc#28]
This is in the question 6:
![image](https://user-images.githubusercontent.com/66573489/185697564-d6fd40a9-3794-4804-99fb-062fad7875e4.png)

What does "cv" mean?

**Comment by wellington36** [comment]
> What does "cv" mean?

Maybe you can find this cv elsewhere in the assignment, maybe not in the exact same form.

**Comment by maxbiostat** [comment]
As @wellington36 says, [_coeficiente de variação_](https://pt.wikipedia.org/wiki/Coeficiente_de_varia%C3%A7%C3%A3o) is mentioned elsewhere in the assignment. The TAs (Tiago and Jairon) might have hints on how to solve question 6.
