### ISSUE TITLE
Erro na solução da A1 de 2021

### ISSUE THREAD

**Issue by wellington36** [maxbiostat/Statistical_Inference_BSc#31]
Na solução da questão 4 item (a), está

![image](https://user-images.githubusercontent.com/61877847/192064181-e3db680c-3c56-4512-8f06-95b34f322e36.png)

O certo acho que seria,

$$
  E_\theta[\delta_H(\textbf{X})] = \frac{\theta}{2} + \frac{1}{n + 1} \theta = \frac{n + 3}{2 (n + 1)} \theta = k_H \theta
$$

**Comment by maxbiostat** [comment]
Isso, mesmo @wellington36 , obrigado. Pode submeter um PR que eu faço o merge.

**Comment by wellington36** [comment]
Notei no tex que uma parte já tinha sido corrigida, só faltava um $\theta$, não compilei o pdf por que não encontrei os gráficos referenciados no tex neste repositório, acredito que o senhor deve ter eles localmente.

**Comment by maxbiostat** [comment]
Resolvido. Figuras no repo agora.

**Comment by wellington36** [comment]
#33 close this.
