### ISSUE TITLE
Code for example 9.1.16 of DeGroot

### ISSUE THREAD

**Issue by adamesalles** [maxbiostat/Statistical_Inference_BSc#34]
Professor, acabei por escrever um código em Julia  para implementar o exemplo utilizado em sala. O senhor gostaria de ver e/ou colocar no repositório?

Fiz em jupyter notebook mas posso converter para script com facilidade, se quiser.

**Comment by maxbiostat** [comment]
Acho ótima ideia. Pode compartilhar o notebook mesmo.
